use_frameworks!

target 'AutoEscuelaComponents_Example' do
  pod 'AutoEscuelaComponents', :path => '../'
  pod 'Reusable'

  target 'AutoEscuelaComponents_Tests' do
    inherit! :search_paths

    
  end
end
